Q.1 Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
print("Output\r",np.arange(2,50,3),"\n")

 [ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47] 



Q.2 Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [7]:
lst = [] 
lst1= []
n = int(input("Enter 5 number of elements list 1 : ")) 
  
# iterating till the range 
for i in range(0, n): 
    ele = int(input())  
    lst.append(ele) 
print("List 1",lst, end=" ") 

k = int(input("Enter 5 number of elements List 2: ")) 
  
# iterating till the range 
for i in range(0, k): 
    ele1 = int(input())  
    lst1.append(ele1) 
print("List 2",lst1, end=" ") 
# converting list to array
arr = np.array(lst)
arr1 = np.array(lst1)  
# displaying array
print ("Array 1st: ", arr)
print ("Array 2nd: ", arr1)

Enter 5 number of elements list 1 : 5
1
2
3
4
5
List 1 [1, 2, 3, 4, 5] Enter 5 number of elements List 2: 5
6
7
8
9
10
List 2 [6, 7, 8, 9, 10] Array 1st:  [1 2 3 4 5]
Array 2nd:  [ 6  7  8  9 10]


In [18]:
arr = np.concatenate((arr,arr1))
print(arr)


[ 1  2  3  4  5  6  7  8  9 10  6  7  8  9 10  6  7  8  9 10  6  7  8  9
 10  6  7  8  9 10]


In [19]:
print(np.sort(arr))

[ 1  2  3  4  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8  8  9  9  9  9
  9 10 10 10 10 10]


Q.3 Write a code snippet to find the dimensions of a ndarray and its size.

In [24]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(type(x))
print("Shape: ",x.shape)
print("Size:",x.size)

<class 'numpy.ndarray'>
Shape:  (2, 3)
Size: 6


Q.4 How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [25]:
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr_1d, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Q.5 Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [27]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Stack:', np.hstack((f, g)))

## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Stack:', np.vstack((f, g)))

Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack: [[1 2 3]
 [4 5 6]]


Q.6 How to get unique items and counts of unique items?

In [30]:
a_list = [1, 1, 2, 2, 3,4,5,5,5,6,7,7,8]

a_set = set(a_list)

number_of_unique_values = len(a_set)
print("Unique Items:",a_set)
print("Unique Count: ",number_of_unique_values)

Unique Items: {1, 2, 3, 4, 5, 6, 7, 8}
Unique Count:  8
